[project]
name = "ee-linux-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "invoke>=2.2.1",
]

[dependency-groups]
dev = [
    "pysnooper>=1.2.3",
]
